- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: installing nodejs
  include_role:
    name: common
    tasks_from: nodejs.yaml



- name: installing systemd
  include_role:
    name: common
    tasks_from: systemd.yaml
