
- name: install mysql
  ansible.builtin.dnf: 
    name: mysql-server
    state:  installed

- name: staring and enabling the mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setting root password for mysql
  ansible.builtin.shell:  mysql_secure_installation --set-root-pass RoboShop@1



