- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: installing nodejs
  include_role:
    name: common
    tasks_from: nodejs.yaml

- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state:  present


- name: load products
  ansible.builtin.shell: mongosh --host  mongodb.chinni.fun < /app/db/master-data.js


- name: installing systemd
  include_role:
    name: common
    tasks_from: systemd.yaml

  






