- name: create roboshop bultin user
  ansible.builtin.user:
    name: roboshop
    shell:  /sbin/nologin
    system: true
    home: /app

- name: create a directory if it is not available
  ansible.builtin.file:
    path: /app
    state:  directory


- name: download "{{ component }}" file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

#this module thinks file exits on ansible control server,needs to extract on to remote machine
#remote_src: yes means files already exist in catalogue server
- name: extract "{{ component }}" code
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes


