

- name: disbaling default node js
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install packages based on package.json.
  community.general.npm:
    path: /app