- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: installing systemd
  include_role:
    name: common
    tasks_from: systemd.yaml