- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: node js setup
  include_role:
    name: common
    tasks_from: nodejs

- name: installing systemd
  include_role:
    name: common
    tasks_from: systemd.yaml